### ISSUE TITLE
getTextViewForDate(final long dayInMillis) null/broken

### ISSUE THREAD

**Issue by pandes** [vdesmet93/holo-calendar-sample#1]
After several months move forward and backward ( sliding tabs).
getTextViewForDate(final long dayInMillis) is null and not change color o propiertes TextView.
In the example, always in "Custom Multi MonthView".
Pressing one day each month and come back backwards, and come back to click a day: broken/null.
thank you very much.

**Comment by vdesmet93** [comment]
I couldn't reproduce the issue with the sample app. The Toast seems to be showing the correct values for me. 
What date format is your device set to?
And do you have some specific steps to reproduce?

**Comment by pandes** [comment]
1) I press one day calendar ( first month) . That's right . The day was made ​​bold.
2) change of month. I press another day calendar ( second month ) . Error.

Always getting " TextView " in CustomMultiMonthView .

Nexus 5 - Android 5.0.1

Thank you very much for answering.

03-04 19:33:19.325: E/AndroidRuntime(24350): FATAL EXCEPTION: main
03-04 19:33:19.325: E/AndroidRuntime(24350): Process: com.vdesmet.sample.calendar, PID: 24350
03-04 19:33:19.325: E/AndroidRuntime(24350): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTypeface(android.graphics.Typeface)' on a null object reference
03-04 19:33:19.325: E/AndroidRuntime(24350):    at com.vdesmet.lib.calendar.MultiCalendarView.getTextViewForDate(MultiCalendarView.java:99)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at com.vdesmet.sample.calendar.activity.CustomMultiMonth.onDayClick(CustomMultiMonth.java:55)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at com.vdesmet.lib.calendar.CalendarView.onClick(CalendarView.java:77)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at android.view.View.performClick(View.java:4756)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at android.view.View$PerformClick.run(View.java:19749)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at android.os.Handler.handleCallback(Handler.java:739)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at android.os.Handler.dispatchMessage(Handler.java:95)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at android.os.Looper.loop(Looper.java:135)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at android.app.ActivityThread.main(ActivityThread.java:5221)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at java.lang.reflect.Method.invoke(Native Method)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at java.lang.reflect.Method.invoke(Method.java:372)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
03-04 19:33:19.325: E/AndroidRuntime(24350):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
